services:
    api:
        build:
            context: ../..
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        environment:
            EXAMPLE_MODULE: "examples.ml_basic:app"
            LOG_FORMAT: json
            LOG_LEVEL: INFO
        restart: unless-stopped
        networks:
            - chapkit-ml

networks:
    chapkit-ml:
        driver: bridge
