"""Migrate an MLproject directory into a chapkit service project."""

from __future__ import annotations

import fnmatch
import json
import re
import shutil
import tomllib
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Annotated, Any, Callable

import typer
import yaml
from jinja2 import Environment, FileSystemLoader, select_autoescape

from chapkit.cli.mlproject import (
    CANONICAL_FILENAMES,
    TYPE_MAP,
    MLProject,
    MLProjectError,
    _coerce_default,
    _python_class_name,
    _python_identifier,
    find_mlproject,
    parse_mlproject,
    python_field_name,
    slugify,
    translate_to_runner_template,
)

_TEMPLATE_DIR = Path(__file__).parent / "templates" / "migrate"
_SHARED_TEMPLATE_DIR = Path(__file__).parent / "templates"

_VALID_BASE_IMAGES = ("chapkit-py", "chapkit-r", "chapkit-r-tidyverse", "chapkit-r-inla")

# Tidyverse-distinctive packages. A `library(<pkg>)` for any of these in a
# root-level R script tips auto-detection from chapkit-r to chapkit-r-tidyverse.
# Only listed packages that aren't usually present in plain-R workflows -
# stuff like `library(yaml)` or `library(jsonlite)` doesn't imply tidyverse.
_TIDYVERSE_HINTS = (
    "tidyverse",
    "dplyr",
    "ggplot2",
    "tidyr",
    "readr",
    "purrr",
    "tibble",
    "fable",
    "tsibble",
    "feasts",
    "forecast",
    "ranger",
    "xgboost",
    "glmnet",
    "lubridate",
    "janitor",
)

# Blocklist. Anything not explicitly chaff stays at root, because migrated
# scripts may read arbitrary data / config files at runtime (e.g. a YAML
# schema loaded by train.py, a JSON config source()d from an R helper). The
# only things we move are the user's chapkit-project-metadata (so our
# freshly-generated main.py / Dockerfile / README win) and obvious ad-hoc
# runners + stale data.
_CHAFF_FILENAMES = {
    # original MLproject definition
    "MLproject",
    "MLproject.yaml",
    "MLproject.yml",
    # user's existing project metadata - we regenerate these
    "README.md",
    "README.rst",
    "README",
    "README.txt",
    ".gitignore",
    ".dockerignore",
    ".python-version",
    "pyproject.toml",
    "requirements.txt",
    # main.py is always regenerated by migrate. Moving any existing one to
    # _old/ keeps re-migrates lossless and prevents silent overwrite of a
    # user-authored main.py. The _check_entry_points_reference_main_py guard
    # below still errors early when the MLproject's entry_points reference
    # main.py as a script - that's a harder conflict (the user needs to
    # rename their runner AND update the entry_points) which chaff-sweeping
    # can't fix on its own.
    "main.py",
    # chapkit scaffold artefacts from a prior greenfield init
    "Makefile",
    "Dockerfile",
    "compose.yml",
    "compose.yaml",
    "CHAPKIT.md",
    # R profile
    ".Rprofile",
}
_CHAFF_DIRS = {"input", "output", "renv"}
_CHAFF_DIR_PATTERNS = ("example_data*", "examples")
_CHAFF_GLOBS_AT_ROOT = (
    "isolated_run.*",
    "evaluate_one_step.py",
    "slides.md",
    "*.pickle",
    "*.rds",
    "*.model",
    "predictions*.csv",
    "training_data*.csv",
    "future_data*.csv",
    "historic_data*.csv",
)

_IGNORE_NAMES = {".git", ".venv", "venv", "__pycache__", ".pytest_cache", ".DS_Store", ".ruff_cache"}
_GENERATED_FILENAMES: tuple[str, ...] = (
    "main.py",
    "pyproject.toml",
    "Dockerfile",
    "compose.yml",
    "Makefile",
    "CHAPKIT.md",
    "README.md",
    "requirements.txt",
    ".gitignore",
    ".dockerignore",
)


class MigrateError(MLProjectError):
    """Raised when migrate cannot proceed."""


class Action(str, Enum):
    """What migrate plans to do with a single path."""

    KEEP = "keep"
    MOVE_TO_OLD = "chaff"
    IGNORE = "ignore"


@dataclass
class ClassifiedPath:
    """A top-level path with its classification decision."""

    path: Path
    action: Action
    reason: str


def classify(project_path: Path) -> list[ClassifiedPath]:
    """Classify every immediate child of the project path."""
    result: list[ClassifiedPath] = []
    for child in sorted(project_path.iterdir()):
        name = child.name
        if name in _IGNORE_NAMES:
            result.append(ClassifiedPath(child, Action.IGNORE, f"ignored ({name})"))
            continue
        if name == "_old":
            result.append(ClassifiedPath(child, Action.IGNORE, "existing _old/ is handled separately"))
            continue
        if child.is_file():
            result.append(_classify_file(child))
        else:
            result.append(_classify_dir(child))
    return result


def _classify_file(path: Path) -> ClassifiedPath:
    name = path.name
    if name in _CHAFF_FILENAMES:
        return ClassifiedPath(path, Action.MOVE_TO_OLD, f"chapkit-owned metadata ({name})")
    for pattern in _CHAFF_GLOBS_AT_ROOT:
        if fnmatch.fnmatch(name, pattern):
            return ClassifiedPath(path, Action.MOVE_TO_OLD, f"matches chaff pattern {pattern!r}")
    return ClassifiedPath(path, Action.KEEP, "kept at root")


def _classify_dir(path: Path) -> ClassifiedPath:
    name = path.name
    if name in _CHAFF_DIRS:
        return ClassifiedPath(path, Action.MOVE_TO_OLD, f"chaff dir {name}/")
    for pattern in _CHAFF_DIR_PATTERNS:
        if fnmatch.fnmatch(name, pattern):
            return ClassifiedPath(path, Action.MOVE_TO_OLD, f"matches chaff dir pattern {pattern!r}")
    return ClassifiedPath(path, Action.KEEP, f"kept directory {name}/")


def _language_from_image(image: str) -> str:
    return {"chapkit-py": "python", "chapkit-r": "r", "chapkit-r-tidyverse": "r", "chapkit-r-inla": "r"}[image]


def _dep_name(requirement: str) -> str:
    """Return the canonical package name from a pep-508 requirement string."""
    head = requirement.split(";", 1)[0].strip()
    name = head.split("[", 1)[0]
    for op in ("==", ">=", "<=", "~=", "!=", ">", "<", " "):
        name = name.split(op, 1)[0]
    return name.strip().lower()


# Deprecated or CRAN-style names some MLproject env files use that need
# rewriting before pip can install them. Keys are lowercase; values are the
# PyPI name to substitute in the generated pyproject.toml dependencies list.
_DEP_ALIASES: dict[str, str] = {
    "sklearn": "scikit-learn",  # "sklearn" on PyPI is a deprecated shim
}


def _rewrite_alias(requirement: str) -> str:
    """Rewrite the package name in a requirement string if it's a known alias."""
    name = _dep_name(requirement)
    alias = _DEP_ALIASES.get(name)
    if alias is None:
        return requirement
    # Replace only the leading package-name token; keep any version/markers.
    stripped = requirement.lstrip()
    leading_ws = requirement[: len(requirement) - len(stripped)]
    tail_start = 0
    for idx, ch in enumerate(stripped):
        if ch in "[=<>!~; " or idx >= len(name):
            tail_start = idx
            break
    else:
        tail_start = len(stripped)
    return f"{leading_ws}{alias}{stripped[tail_start:]}"


# Inline-comment stripper for requirements.txt lines. pip's rule: a whitespace-
# prefixed `#` starts a comment; bare `#` is part of the value (direct-URL /
# VCS fragments like `#sha256=...` or `#subdirectory=src` must survive).
_REQUIREMENTS_INLINE_COMMENT = re.compile(r"\s+#.*$")

# Directive flags that carry index configuration and should flow through into
# the generated requirements.txt so uv / pip can honour the user's private
# indexes. Each accepts a value (either space-separated or `=` attached).
_REQUIREMENTS_INDEX_DIRECTIVES = (
    "--index-url",
    "--extra-index-url",
    "--find-links",
    "--trusted-host",
    "--no-index",
    "--pre",
)


def _parse_requirements_file(
    path: Path,
    project_root: Path,
    seen_files: set[Path],
    add_dep: Callable[[str], None],
    add_index_option: Callable[[str], None],
) -> None:
    """Parse a requirements.txt file, recursing into `-r` includes.

    Follows pip's semantics: `-r other.txt` / `--requirement other.txt` resolves
    relative to the including file and is pulled in transitively (cycles are
    short-circuited via `seen_files`). `-c constraints.txt` is preserved as an
    index option, with the path rewritten to be relative to `project_root` so
    the generated root-level requirements.txt resolves it correctly - a
    nested file's `-c constraints.txt` means `<nested_dir>/constraints.txt`,
    which from the root requirements.txt needs to become e.g.
    `-c sub/constraints.txt`.

    Installable requirements are handed to `add_dep`; index-configuration
    directives (`--extra-index-url`, `-c`, ...) are handed to
    `add_index_option` for verbatim emission into the generated
    requirements.txt. Unrecognized directives print a warning rather than
    getting silently dropped, so users notice anything we couldn't translate.
    """
    resolved = path.resolve()
    if resolved in seen_files or not resolved.is_file():
        return
    seen_files.add(resolved)
    try:
        raw_text = resolved.read_text(encoding="utf-8")
    except OSError:
        return

    def _rewrite_path_for_root(value: str) -> str:
        """Turn a path relative to the current file into one relative to project_root.

        URLs (anything containing `://`, including `file://`, `http(s)://`,
        `git+https://`) and absolute filesystem paths pass through unchanged.
        Everything else is resolved against the current file's parent and
        re-expressed relative to project_root; when the target escapes the
        project root (e.g. `../sibling/foo.txt`) we fall back to the absolute
        form rather than emit a misleading relative path.
        """
        if "://" in value:
            return value
        candidate = Path(value)
        if candidate.is_absolute():
            return str(candidate)
        abs_path = (resolved.parent / candidate).resolve()
        try:
            return abs_path.relative_to(project_root.resolve()).as_posix()
        except ValueError:
            return str(abs_path)

    for raw_line in raw_text.splitlines():
        stripped_leading = raw_line.lstrip()
        if not stripped_leading or stripped_leading.startswith("#"):
            continue
        # Strip inline whitespace-prefixed comment (preserves URL fragments).
        line = _REQUIREMENTS_INLINE_COMMENT.sub("", raw_line).strip()
        if not line:
            continue

        # Directive handling.
        # - `-r` / `--requirement` recurses: its entries are installable deps,
        #   we inline them so the generated requirements.txt is self-contained.
        # - `-c` / `--constraint` and `--find-links` carry paths that the user
        #   wrote relative to the including file. We preserve them as index
        #   options but rewrite relative paths to be relative to project_root
        #   (the generated root-level requirements.txt's directory), so uv
        #   resolves them regardless of how deeply nested the original
        #   directive was. URL forms (`file://`, `https://`, ...) pass
        #   through untouched.
        # - Other index directives (`--extra-index-url`, `--index-url`,
        #   `--trusted-host`, `--no-index`, `--pre`) are URL- or flag-only
        #   and preserved verbatim.
        # - `-e .` is silently skipped (migrated project is a service, not
        #   an installable package).
        # - Anything else prints a warning.
        if line.startswith("-"):
            tokens = line.split(None, 1)
            flag = tokens[0]
            rest = tokens[1] if len(tokens) == 2 else ""
            # Handle `--flag=value` form too.
            if "=" in flag and flag.startswith("--"):
                flag, _, rest = flag.partition("=")
            if flag in ("-r", "--requirement"):
                if rest:
                    _parse_requirements_file(
                        (resolved.parent / rest).resolve(),
                        project_root,
                        seen_files,
                        add_dep,
                        add_index_option,
                    )
                continue
            if flag in ("-c", "--constraint"):
                if rest:
                    add_index_option(f"-c {_rewrite_path_for_root(rest)}")
                continue
            if flag == "--find-links":
                if rest:
                    add_index_option(f"--find-links {_rewrite_path_for_root(rest)}")
                continue
            if flag in _REQUIREMENTS_INDEX_DIRECTIVES:
                add_index_option(line if rest else flag)
                continue
            if flag in ("-e", "--editable") and rest.strip() in (".", "./"):
                continue
            typer.echo(
                f"Warning: ignoring unrecognized directive in {resolved}: {line}",
                err=True,
            )
            continue

        add_dep(line)


def _extract_user_dependencies(
    project_path: Path,
    mlproject: MLProject | None = None,
) -> tuple[list[str], list[str]]:
    """Collect user's Python deps and index options from pyproject / requirements.txt / env YAMLs.

    Returns `(deps, index_options)`:
    - `deps` are raw requirement strings ("pandas>=2.0", "numpy", ...)
      deduplicated by canonical package name (first occurrence wins). Any
      chapkit entry is stripped (the generated pyproject.toml pins its own).
    - `index_options` are verbatim pip / uv directive lines (e.g.
      `--extra-index-url https://internal.example.org/simple`) lifted from
      requirements.txt so private indexes still resolve at image build time.

    Sources, in order of precedence:
    1. pyproject.toml [project.dependencies] at the project root
    2. requirements.txt at the project root. `-r other.txt` is followed
       recursively (cycle-safe) and its entries inlined as deps. `-c
       constraints.txt` is preserved verbatim at the top of the generated
       requirements.txt (constraint files bound versions for already-installed
       packages; recursing them would install things the user didn't ask for).
       `--extra-index-url` and friends are preserved; `-e .` is silently
       skipped; anything else prints a warning.
    3. MLproject's python_env / conda_env file (MLflow-style YAML with a
       `dependencies:` list). Simple scalar deps are kept verbatim; nested
       pip-sub-dict entries inside a conda env are flattened.
    """
    seen: set[str] = set()
    kept: list[str] = []
    index_options: list[str] = []
    seen_index_options: set[str] = set()

    def _add(requirement: object) -> None:
        if not isinstance(requirement, str):
            return
        rewritten = _rewrite_alias(requirement)
        name = _dep_name(rewritten)
        if not name or name == "chapkit" or name in seen:
            return
        seen.add(name)
        kept.append(rewritten.strip())

    def _add_index_option(option: str) -> None:
        option = option.strip()
        if not option or option in seen_index_options:
            return
        seen_index_options.add(option)
        index_options.append(option)

    pyproject = project_path / "pyproject.toml"
    if pyproject.is_file():
        try:
            with pyproject.open("rb") as toml_handle:
                data = tomllib.load(toml_handle)
        except (tomllib.TOMLDecodeError, OSError):
            data = {}
        raw = data.get("project", {}).get("dependencies", [])
        if isinstance(raw, list):
            for entry in raw:
                _add(entry)

    requirements_path = project_path / "requirements.txt"
    if requirements_path.is_file():
        _parse_requirements_file(requirements_path, project_path, set(), _add, _add_index_option)

    # Candidate env files: first the ones the MLproject explicitly points at,
    # then a fallback scan for conventional filenames at the project root when
    # the MLproject is silent about its Python env (e.g. uses docker_env only).
    # Many chap-models repos ship a pyenv.yaml alongside a docker_env-only
    # MLproject, so without the fallback their deps never reach the image.
    env_candidates: list[Path] = []
    if mlproject is not None:
        for env_key in ("python_env", "conda_env"):
            env_file = mlproject.env_hints.get(env_key)
            if env_file:
                env_candidates.append(project_path / env_file)

    if not env_candidates:
        for conventional in (
            "pyenv.yaml",
            "pyenv.yml",
            "conda.yaml",
            "conda.yml",
            "environment.yaml",
            "environment.yml",
        ):
            fallback_path = project_path / conventional
            if fallback_path.is_file():
                env_candidates.append(fallback_path)
                break

    for env_path in env_candidates:
        if not env_path.is_file():
            continue
        try:
            with env_path.open("r", encoding="utf-8") as yaml_handle:
                env_data = yaml.safe_load(yaml_handle)
        except (yaml.YAMLError, OSError):
            continue
        if not isinstance(env_data, dict):
            continue
        raw_deps = env_data.get("dependencies", []) or []
        # Detect conda-style: any dict-entry with a `pip:` list, or conventional
        # conda filenames, or MLproject's conda_env pointer. In conda files the
        # top-level `dependencies:` mixes conda packages (python=3.11, bare
        # `pip`, conda-forge::pkg, ...) with a nested `{pip: [...]}` block - only
        # the pip block is pip-installable, the rest is conda-native syntax that
        # would break `uv pip install` if passed through.
        is_conda = (
            env_path.name in ("conda.yaml", "conda.yml", "environment.yaml", "environment.yml")
            or (
                mlproject is not None
                and mlproject.env_hints.get("conda_env")
                and (project_path / mlproject.env_hints["conda_env"]).resolve() == env_path.resolve()
            )
            or any(isinstance(entry, dict) and "pip" in entry for entry in raw_deps)
        )
        for entry in raw_deps:
            if isinstance(entry, dict):
                for key, sublist in entry.items():
                    if key == "pip" and isinstance(sublist, list):
                        for sub in sublist:
                            _add(sub)
            elif is_conda:
                # Skip conda-native scalars (python=3.11, pip, conda-forge::pkg, ...)
                # that aren't pip-installable as-is.
                continue
            else:
                _add(entry)
    return kept, index_options


def _split_index_options_for_pyproject(
    options: list[str],
    project_root: Path,
) -> dict[str, Any]:
    """Classify raw requirements.txt directive lines into pyproject [tool.uv] buckets.

    The Dockerfile path installs via `-r requirements.txt` and honours the raw
    directive block verbatim. The local `uv sync` path reads pyproject.toml,
    which needs the same install context expressed as `[tool.uv]` keys so
    private indexes resolve and constraint files actually bind versions.

    Recognised flags:
      --index-url URL         -> UV_INDEX_URL              (string)
      --extra-index-url URL   -> UV_EXTRA_INDEX_URLS       (list of strings)
      --find-links PATH_OR_URL-> UV_FIND_LINKS             (list of strings)
      --no-index              -> UV_NO_INDEX               (bool)
      --pre                   -> UV_PRE                    (bool; uv renders as prerelease = "allow")
      -c PATH                 -> UV_CONSTRAINT_DEPENDENCIES (list of PEP 508 specs, inlined from the file)
      --trusted-host HOST     -> deliberately dropped; uv has no pyproject key for this

    For `-c <path>` the path is already relative to `project_root` (rewritten
    by _parse_requirements_file), so we resolve it there, read the file, and
    inline each non-directive requirement spec into constraint-dependencies.
    URL-form `-c` values (rare) are ignored here - they only work at install
    time through the Dockerfile's `-r requirements.txt` path.
    """
    extra_index_urls: list[str] = []
    find_links: list[str] = []
    index_url: str | None = None
    constraint_deps: list[str] = []
    seen_constraints: set[str] = set()
    no_index = False
    pre = False
    for option in options:
        tokens = option.split(None, 1)
        if not tokens:
            continue
        flag = tokens[0]
        rest = tokens[1].strip() if len(tokens) == 2 else ""
        if flag == "--index-url" and rest:
            index_url = rest
        elif flag == "--extra-index-url" and rest:
            if rest not in extra_index_urls:
                extra_index_urls.append(rest)
        elif flag == "--find-links" and rest:
            if rest not in find_links:
                find_links.append(rest)
        elif flag == "--no-index":
            no_index = True
        elif flag == "--pre":
            pre = True
        elif flag == "-c" and rest and "://" not in rest:
            target = (project_root / rest).resolve()
            try:
                constraint_text = target.read_text(encoding="utf-8")
            except OSError:
                continue
            for raw_line in constraint_text.splitlines():
                stripped_leading = raw_line.lstrip()
                if not stripped_leading or stripped_leading.startswith("#"):
                    continue
                head = _REQUIREMENTS_INLINE_COMMENT.sub("", raw_line).strip()
                if not head or head.startswith("-"):
                    # Nested directives in a constraint file are not expressible as
                    # [tool.uv].constraint-dependencies entries; the docker path
                    # still honours them via the raw -r/-c pass-through.
                    continue
                if _dep_name(head) in seen_constraints:
                    continue
                seen_constraints.add(_dep_name(head))
                constraint_deps.append(head)
    return {
        "UV_INDEX_URL": index_url,
        "UV_EXTRA_INDEX_URLS": extra_index_urls,
        "UV_FIND_LINKS": find_links,
        "UV_CONSTRAINT_DEPENDENCIES": constraint_deps,
        "UV_NO_INDEX": no_index,
        "UV_PRE": pre,
    }


_MAIN_PY_REF_RE = re.compile(r"(?:(?<=^)|(?<=[/\s]))main\.py(?=\s|$)")


def _check_entry_points_reference_main_py(mlproject: MLProject) -> None:
    """Error if any entry_point command references main.py as a script file.

    Migrate generates a chapkit FastAPI service at main.py. If the MLproject's
    train/predict commands invoke `python main.py ...` as a CLI (like
    chap-models/chap_pymc does via a cyclopts runner), the two main.py's collide:
    after migrate, `python main.py train ...` would call the chapkit service
    with "train" as an argument and fail at runtime.

    The fix is on the user's side and mechanical: rename their runner (e.g.
    main.py -> cli.py), update the MLproject's entry_points to match, then
    re-run migrate. Surfaced here as an early error so no files get written.
    """
    offenders: list[str] = []
    for ep_name, ep in mlproject.entry_points.items():
        if _MAIN_PY_REF_RE.search(ep.command):
            offenders.append(f"{ep_name}: {ep.command}")
    if not offenders:
        return
    joined = "\n  ".join(offenders)
    raise MigrateError(
        "MLproject entry_point command(s) reference main.py, but chapkit mlproject migrate "
        "also generates a main.py (the FastAPI service) - the two cannot coexist at the "
        "project root.\n\n"
        f"Offending entry_point(s):\n  {joined}\n\n"
        "Rename your script (e.g. main.py -> cli.py or runner.py), update the MLproject's "
        "entry_points commands to match, then re-run `chapkit mlproject migrate`. Your "
        "renamed file will stay at the project root and the generated commands in the new "
        "main.py will invoke it correctly."
    )


def _any_r_script_uses(project_path: Path, packages: tuple[str, ...]) -> bool:
    for script in project_path.glob("*.[rR]"):
        try:
            text = script.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        for pkg in packages:
            if f"library({pkg})" in text or f'library("{pkg}")' in text:
                return True
    return False


def detect_base_image(
    project_path: Path,
    mlproject: MLProject,
    override: str | None,
) -> tuple[str, str, str]:
    """Return (base_image, language, rationale)."""
    if override is not None:
        if override not in _VALID_BASE_IMAGES:
            raise MigrateError(f"--base-image must be one of {', '.join(_VALID_BASE_IMAGES)}; got {override!r}")
        return override, _language_from_image(override), f"explicit --base-image {override}"

    r_scripts = list(project_path.glob("*.r")) + list(project_path.glob("*.R"))
    py_scripts = list(project_path.glob("*.py"))
    docker_env = mlproject.env_hints.get("docker_env", "")
    env_suggests_inla = "docker_r_inla" in docker_env
    uses_inla = env_suggests_inla or _any_r_script_uses(project_path, ("INLA", "fmesher", "inla"))

    if r_scripts and py_scripts:
        rationale = "found both R and Python scripts; chapkit-r-inla covers both"
        return "chapkit-r-inla", "mixed", rationale
    if r_scripts:
        if uses_inla:
            hint = "MLproject declares docker_r_inla" if env_suggests_inla else "R script imports INLA"
            return "chapkit-r-inla", "r", f"R + INLA ({hint})"
        if _any_r_script_uses(project_path, _TIDYVERSE_HINTS):
            return "chapkit-r-tidyverse", "r", "R + tidyverse stack (tidyverse/fable/forecast/etc. detected)"
        return "chapkit-r", "r", "R scripts, no INLA or tidyverse hints detected"
    if py_scripts:
        return "chapkit-py", "python", "Python scripts only"
    raise MigrateError("No Python (.py) or R (.r/.R) scripts at the project root; cannot pick a base image.")


_VALID_ASSESSED_STATUS = {"gray", "red", "orange", "yellow", "green"}
_VALID_PERIOD_TYPES = {"weekly", "monthly"}


def build_service_info_context(mlproject: MLProject) -> dict[str, Any]:
    """Build the ModelMetadata + capability-constraints block for MLServiceInfo.

    Handles the MLproject -> chapkit vocabulary mismatches:
    - MLproject `supported_period_type: any` becomes `monthly` (chapkit's
      PeriodType only has weekly/monthly); otherwise the declared value
      passes through if recognised, else `monthly`.
    - `author_assessed_status` is validated against chapkit's AssessedStatus
      enum; unknown values fall back to None.
    - URL-typed fields (organization_logo_url, repository_url,
      documentation_url) are only emitted if the value looks like a URL
      (starts with http:// or https://) - MLServiceInfo validates them as
      HttpUrl and we don't want to crash on a free-text slot.
    """
    meta = mlproject.meta_data

    def _str_or_none(key: str) -> str | None:
        value = meta.get(key)
        if value is None:
            return None
        text = str(value).strip()
        return text or None

    def _url_or_none(key: str) -> str | None:
        value = _str_or_none(key)
        if value and (value.startswith("http://") or value.startswith("https://")):
            return value
        return None

    assessed_raw = _str_or_none("author_assessed_status")
    assessed_status = assessed_raw if assessed_raw in _VALID_ASSESSED_STATUS else None

    period_raw = (mlproject.supported_period_type or "").strip().lower()
    if period_raw in _VALID_PERIOD_TYPES:
        period_type = period_raw
    else:
        period_type = "monthly"

    return {
        "META_AUTHOR": _str_or_none("author"),
        "META_AUTHOR_NOTE": _str_or_none("author_note") or _str_or_none("description"),
        "META_ASSESSED_STATUS": assessed_status,
        "META_CONTACT_EMAIL": _str_or_none("contact_email"),
        "META_ORGANIZATION": _str_or_none("organization"),
        "META_ORGANIZATION_LOGO_URL": _url_or_none("organization_logo_url"),
        "META_CITATION_INFO": _str_or_none("citation_info"),
        "META_REPOSITORY_URL": _url_or_none("repository_url") or _url_or_none("source_url"),
        "META_DOCUMENTATION_URL": _url_or_none("documentation_url"),
        "PERIOD_TYPE": period_type,
        "REQUIRED_COVARIATES": list(mlproject.required_covariates),
        "ALLOW_FREE_COVARIATES": mlproject.allow_free_additional_continuous_covariates,
        "REQUIRES_GEO": mlproject.requires_geo,
    }


def build_config_fields(mlproject: MLProject) -> list[tuple[str, str, str, str | None, str | None]]:
    """Turn MLproject user_options into (field_name, python_type, default_repr, description, alias) tuples.

    `alias` is populated only when the MLproject option name is not already a valid Python
    identifier - the generated Field then uses `alias="<original>"` so the wire contract
    (POSTed configs, config.yml keys) keeps the original name while Python code uses the
    sanitized identifier.
    """
    type_names = {int: "int", float: "float", str: "str", bool: "bool"}
    fields: list[tuple[str, str, str, str | None, str | None]] = []
    seen: set[str] = set()
    for opt_name, opt_body in mlproject.user_options.items():
        declared_type = str(opt_body.get("type", "string")).lower()
        py_type = TYPE_MAP.get(declared_type, str)
        type_name = type_names.get(py_type, "str")
        if "default" in opt_body:
            coerced = _coerce_default(opt_body["default"], py_type)
            default_repr = repr(coerced)
        else:
            default_repr = "..."
        raw_desc = opt_body.get("description")
        description = str(raw_desc).strip() if isinstance(raw_desc, str) and raw_desc.strip() else None
        field_name = python_field_name(opt_name)
        alias = opt_name if field_name != opt_name else None
        if field_name in seen:
            raise MigrateError(
                f"user_option {opt_name!r} normalizes to {field_name!r}, which collides with an earlier option"
            )
        fields.append((field_name, type_name, default_repr, description, alias))
        seen.add(field_name)
    if "prediction_periods" not in seen:
        fields.insert(
            0,
            ("prediction_periods", "int", "3", "Number of periods to predict into the future.", None),
        )
    return fields


def _render(template_dir: Path, template_name: str, context: dict[str, Any]) -> str:
    env = Environment(
        loader=FileSystemLoader([template_dir, _SHARED_TEMPLATE_DIR]),
        autoescape=select_autoescape(),
        trim_blocks=True,
        lstrip_blocks=True,
    )
    # Jinja's built-in `tojson` filter always wraps output with htmlsafe_json_dumps,
    # which escapes <, >, &, ' as unicode sequences (`>` -> `>`). That's correct
    # for HTML but unreadable in Python / TOML / YAML output, turning `chapkit>=0.19`
    # into `chapkit>=0.19`. Override `tojson` with plain json.dumps so literals
    # stay readable; our templates are never HTML.
    env.filters["tojson"] = json.dumps
    return env.get_template(template_name).render(**context)


def _parse_param_overrides(raw: list[str] | None) -> dict[str, str]:
    overrides: dict[str, str] = {}
    if not raw:
        return overrides
    for entry in raw:
        if "=" not in entry:
            raise typer.BadParameter(f"--param expects NAME=FILENAME, got: {entry}")
        name, _, value = entry.partition("=")
        name, value = name.strip(), value.strip()
        if not name or not value:
            raise typer.BadParameter(f"--param expects NAME=FILENAME, got: {entry}")
        overrides[name] = value
    return overrides


def _collect_unknown_params(command: str, known: dict[str, str]) -> list[str]:
    import string as _string

    missing: list[str] = []
    for _, field_name, _, _ in _string.Formatter().parse(command):
        if not field_name:
            continue
        base = field_name.split(".", 1)[0].split("[", 1)[0]
        if base not in known and base not in missing:
            missing.append(base)
    return missing


def _resolve_unknown_params(
    mlproject: MLProject,
    overrides: dict[str, str],
    assume_yes: bool,
) -> dict[str, str]:
    known = {**CANONICAL_FILENAMES, **overrides}
    for ep_name in ("train", "predict"):
        command = mlproject.entry_points[ep_name].command
        missing = _collect_unknown_params(command, known)
        for param in missing:
            if assume_yes:
                raise MigrateError(
                    f"Unknown MLproject parameter {{{param}}} in {ep_name!r}; "
                    "rerun without --yes to answer interactively, or pass --param."
                )
            filename = typer.prompt(
                f"MLproject parameter {{{param}}} has no canonical mapping. Filename to substitute (e.g. data.csv)"
            ).strip()
            if not filename:
                raise MigrateError(f"Empty filename for {{{param}}}; aborting.")
            overrides[param] = filename
            known[param] = filename
    return overrides


def _resolve_base_image(
    project_path: Path,
    mlproject: MLProject,
    override: str | None,
    assume_yes: bool,
) -> tuple[str, str]:
    base_image, language, rationale = detect_base_image(project_path, mlproject, override)
    typer.echo(f"  base image: ghcr.io/dhis2-chap/{base_image}  ({rationale})")
    if language == "mixed" and override is None and not assume_yes:
        if not typer.confirm("Using chapkit-r-inla to cover both languages. OK?", default=True):
            raise typer.Exit(code=1)
    return base_image, language


def _print_plan(
    project_path: Path,
    plan: list[ClassifiedPath],
    renders: list[str],
    base_image: str,
) -> None:
    typer.echo("")
    typer.echo(f"Plan for {project_path}:")
    typer.echo(f"  base image: ghcr.io/dhis2-chap/{base_image}:latest")
    typer.echo("")
    typer.echo("  Paths:")
    for item in plan:
        if item.action is Action.IGNORE:
            continue
        marker = "keep" if item.action is Action.KEEP else "-> _old/"
        typer.echo(f"    {marker:9s} {item.path.name}  ({item.reason})")
    typer.echo("")
    typer.echo("  Files to generate at root:")
    for filename in renders:
        typer.echo(f"    write  {filename}")
    typer.echo("")


def _execute_moves(plan: list[ClassifiedPath], old_dir: Path) -> int:
    moved = 0
    for item in plan:
        if item.action is not Action.MOVE_TO_OLD:
            continue
        dest = old_dir / item.path.name
        shutil.move(str(item.path), str(dest))
        moved += 1
    return moved


def _execute_writes(
    project_path: Path,
    renders: list[str],
    rendered: dict[str, str],
) -> int:
    # `renders` lists every filename chapkit might generate; `rendered` only
    # contains the ones actually produced (e.g. requirements.txt is skipped
    # for R projects or Python projects with no user deps). Only write what
    # was rendered - skipping a filename just means it isn't needed here.
    written = 0
    for filename in renders:
        if filename in rendered:
            (project_path / filename).write_text(rendered[filename])
            written += 1
    return written


def migrate_command(
    path: Annotated[
        Path,
        typer.Argument(help="Directory containing the MLproject file (default: current directory)."),
    ] = Path("."),
    base_image: Annotated[
        str | None,
        typer.Option(
            "--base-image",
            help="Override base image (chapkit-py, chapkit-r, chapkit-r-tidyverse, chapkit-r-inla).",
        ),
    ] = None,
    dry_run: Annotated[
        bool,
        typer.Option("--dry-run", help="Print the plan without touching any files."),
    ] = False,
    yes: Annotated[
        bool,
        typer.Option("--yes", "-y", help="Skip confirmation prompts (for scripting / CI)."),
    ] = False,
    param: Annotated[
        list[str] | None,
        typer.Option(
            "--param",
            help="Override the filename substituted for an MLproject parameter (repeatable).",
        ),
    ] = None,
) -> None:
    """Adopt an existing MLproject directory as a chapkit project."""
    project_path = path.resolve()
    try:
        _run(project_path, base_image, dry_run, yes, param)
    except MigrateError as error:
        typer.echo(f"Error: {error}", err=True)
        raise typer.Exit(code=1) from error
    except MLProjectError as error:
        typer.echo(f"Error: {error}", err=True)
        raise typer.Exit(code=1) from error


def _run(
    project_path: Path,
    base_image: str | None,
    dry_run: bool,
    assume_yes: bool,
    param: list[str] | None,
) -> None:
    old_dir = project_path / "_old"
    if old_dir.exists() and not dry_run:
        raise MigrateError(f"{old_dir} already exists. Rename or remove it before re-running migrate.")

    mlproject_file = find_mlproject(project_path)
    mlproject = parse_mlproject(mlproject_file)
    typer.echo(f"Found MLproject: {mlproject_file} (name={mlproject.name!r})")

    _check_entry_points_reference_main_py(mlproject)

    overrides = _parse_param_overrides(param)
    overrides = _resolve_unknown_params(mlproject, overrides, assume_yes)

    # Emit commands in ShellModelRunner-template form ({data_file}, etc.) so the
    # generated main.py is decoupled from the concrete workspace filenames.
    train_command = translate_to_runner_template(mlproject.entry_points["train"].command, overrides)
    predict_command = translate_to_runner_template(mlproject.entry_points["predict"].command, overrides)

    resolved_base_image, language = _resolve_base_image(project_path, mlproject, base_image, assume_yes)

    plan = classify(project_path)

    # Everything except source files / lockfiles / LICENSE / .github/ has been
    # bucketed as MOVE_TO_OLD, so by the time we generate files at root there
    # is nothing left to collide with. That includes any existing README.md,
    # pyproject.toml, .gitignore, .dockerignore, etc. - they land in _old/.
    renders = list(_GENERATED_FILENAMES)

    user_deps, user_index_options = _extract_user_dependencies(project_path, mlproject)
    uv_pyproject_options = _split_index_options_for_pyproject(user_index_options, project_path)
    # Prefer a meta_data description from the MLproject for the service description
    # (e.g. ewars_template has a nice paragraph). Fall back to our generic template.
    meta_description = mlproject.meta_data.get("description")
    if isinstance(meta_description, str) and meta_description.strip():
        project_description = meta_description.strip()
    else:
        project_description = f"chapkit service migrated from the {mlproject.name} MLproject"
    meta_display_name = mlproject.meta_data.get("display_name")
    if isinstance(meta_display_name, str) and meta_display_name.strip():
        project_display_name = meta_display_name.strip()
    else:
        project_display_name = mlproject.name

    context: dict[str, Any] = {
        "PROJECT_NAME": mlproject.name,
        "PROJECT_DISPLAY_NAME": project_display_name,
        "PROJECT_SLUG": slugify(mlproject.name),
        "PROJECT_IDENTIFIER": _python_identifier(mlproject.name),
        "PROJECT_CLASS_NAME": _python_class_name(mlproject.name),
        "PROJECT_DESCRIPTION": project_description,
        "BASE_IMAGE": resolved_base_image,
        "LANGUAGE": language,
        "TRAIN_COMMAND": train_command,
        "PREDICT_COMMAND": predict_command,
        "CONFIG_FIELDS": build_config_fields(mlproject),
        "HAS_RENV": (project_path / "renv.lock").is_file(),
        "HAS_INSTALL_PACKAGES_R": (project_path / "install_packages.R").is_file(),
        "HAS_USER_PYPROJECT": (project_path / "pyproject.toml").is_file(),
        "USER_DEPENDENCIES": user_deps,
        "USER_INDEX_OPTIONS": user_index_options,
        **uv_pyproject_options,
        "CHAPKIT_VERSION": _get_chapkit_version(),
        **build_service_info_context(mlproject),
    }

    rendered = _render_all(context)

    # Only show files we will actually render in the plan output. requirements.txt
    # is Python-and-has-deps conditional (see _render_all); other filenames are
    # unconditional but this keeps the plan honest if we ever add more.
    planned_renders = [name for name in renders if name in rendered]
    _print_plan(project_path, plan, planned_renders, resolved_base_image)

    if dry_run:
        typer.echo("Dry run: no files changed.")
        return

    if not assume_yes:
        if not typer.confirm("Proceed?", default=True):
            typer.echo("Aborted.")
            raise typer.Exit(code=1)

    old_dir.mkdir()
    moved = _execute_moves(plan, old_dir)
    written = _execute_writes(project_path, renders, rendered)

    typer.echo("")
    typer.echo(f"Moved {moved} item(s) to _old/.")
    typer.echo(f"Generated {written} file(s) at project root.")
    if user_deps:
        typer.echo(f"Merged {len(user_deps)} dependency(ies) from the original pyproject.toml into the new one.")
    if (old_dir / "pyproject.toml").is_file():
        typer.echo("Your original pyproject.toml is preserved at _old/pyproject.toml for reference.")

    # Unpinned runtime deps resolve to latest PyPI at docker build, which can
    # silently break scripts that rely on older APIs (e.g. pandas 2.1 removed
    # fillna(method=...)). We don't invent pins - that would be guessing - but
    # we do point at the deps so the model author can pin them before shipping.
    unpinned = [dep for dep in user_deps if _dep_name(dep) == dep.strip().lower()]
    if unpinned:
        typer.echo("")
        typer.echo(
            f"Note: {len(unpinned)} dependency(ies) are unpinned - "
            "docker build will resolve them to whatever is latest on PyPI. "
            "Pin them in pyproject.toml (or upstream in pyenv.yaml / conda.yaml / python_env) "
            "to lock reproducible builds:"
        )
        for dep in unpinned:
            typer.echo(f"  - {dep}")
    typer.echo("")
    typer.echo("Next steps:")
    typer.echo("  uv sync && uv run python main.py")
    typer.echo(
        f"  # or: docker build -t {context['PROJECT_SLUG']} . && docker run --rm -p 9090:8000 {context['PROJECT_SLUG']}"
    )
    typer.echo("See CHAPKIT.md for more.")


def _render_all(context: dict[str, Any]) -> dict[str, str]:
    t = _TEMPLATE_DIR
    rendered: dict[str, str] = {
        "main.py": _render(t, "main_migrate.py.jinja2", context),
        "pyproject.toml": _render(t, "pyproject_migrate.toml.jinja2", context),
        "Dockerfile": _render(t, "Dockerfile_migrate.jinja2", context),
        "compose.yml": _render(_SHARED_TEMPLATE_DIR, "compose.yml.jinja2", context),
        "Makefile": _render(t, "Makefile_migrate.jinja2", context),
        "CHAPKIT.md": _render(t, "CHAPKIT_migrate.md.jinja2", context),
        "README.md": _render(t, "README_migrate.md.jinja2", context),
        ".gitignore": _render(t, "gitignore_migrate.jinja2", context),
        ".dockerignore": _render(t, "dockerignore_migrate.jinja2", context),
    }
    # Emit requirements.txt for Python projects with deps so any pip-style tooling
    # downstream still has the canonical install list. The Dockerfile path now uses
    # `uv sync` from pyproject.toml + uv.lock, so this file isn't wired into the
    # image build - it's kept for reference and to preserve directives (notably
    # --trusted-host) that don't translate cleanly into pyproject's [tool.uv].
    if context.get("LANGUAGE") == "python" and context.get("USER_DEPENDENCIES"):
        rendered["requirements.txt"] = _render(t, "requirements_migrate.txt.jinja2", context)
    return rendered


#: Floor for the `chapkit>=...` dep that migrate emits into the generated
#: pyproject.toml. This is the minimum chapkit release that has the runtime
#: bits the generated main.py and Dockerfile CMD depend on. It's explicitly
#: NOT the running chapkit's own version, because that could be a `.devN`
#: not-yet-published release and would leave the migrated project with an
#: uninstallable dep.
_MIN_CHAPKIT_VERSION = "0.23.0"


def _get_chapkit_version() -> str:
    return _MIN_CHAPKIT_VERSION
