[project]
name = "chapkit-demo-quickstart"
version = "0.1.0"
description = "CLI demo for persisting and retrieving typed configuration with ConfigManager"
requires-python = ">=3.13"
dependencies = [
    "chapkit",
]

[tool.uv.sources]
chapkit = { path = "../..", editable = true }
